pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/PROYECTOS-APP/licencia-app-backend.git',
                    credentialsId: 'Ardamins'
            }
        }

        stage('Install') {
            steps {
                bat 'npm install --legacy-peer-deps'
            }
        }

        stage('Build') {
            steps {
                bat 'npm run build --prod'
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'www/**/*'
            }
        }
    }
}